apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  tssc/gitops: bk6az2oon-nodejs 
  janus-idp.io/tekton: bk6az2oon-nodejs
  backstage.io/kubernetes-id: bk6az2oon-nodejs
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: bk6az2oon-nodejs
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml