apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: bk6az2oon-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: bk6az2oon-nodejs 
  name: bk6az2oon-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: bk6az2oon-nodejs 
